name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the OpenJDK 11 image
      run: docker build ./openjdk11-alpine --file ./openjdk11-alpine/Dockerfile --tag nicocartalla/openjdk:11-alpine
    - name: Build the OpenJDK 8 image
      run: docker build ./openjdk8-alpine --file ./openjdk8-alpine/Dockerfile --tag nicocartalla/openjdk:8-alpine
      
    - name: Docker Push OpenJDK 11
      run: docker push nicocartalla/openjdk:11-alpine
    - name: Docker Push OpenJDK 8
      run: docker push nicocartalla/openjdk:8-alpine
